[metadata]
version = "1.0"

[versions]
junit = "5.9.0"
cloud = "1.7.1"
javelin = "1.2.0"
owner = "1.0.12"
immutables = "2.9.2"
distributor = "3.0.0-rc.3"
gson = "2.10"
mindustry = "140"
mongodb = "4.8.0"
password4j = "1.6.2"
nullaway = "0.9.4"
errorprone-core = "2.10.0"
errorprone-gradle = "2.0.2"
checkerframework = "3.26.0"
javacord = "3.7.0"
log4j-to-slf4j = "2.14.1"
slf4j = "2.0.5"
auto = "1.0.1"

# plugins
indra = "3.0.1"
toxopid = "2.2.0"
spotless = "6.11.0"
shadow = "7.1.2"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-core" }
errorprone-gradle = { module = "net.ltgt.gradle:gradle-errorprone-plugin", version.ref = "errorprone-gradle" }
checkerframework = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }
immutables-value-annotations = { module = "org.immutables:value-annotations", version.ref = "immutables" }
immutables-value-processor = { module = "org.immutables:value-processor", version.ref = "immutables" }
javelin-core = { module = "fr.xpdustry:javelin-core", version.ref = "javelin" }
javelin-mindustry = { module = "fr.xpdustry:javelin-mindustry", version.ref = "javelin" }
mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
password4j = { module = "com.password4j:password4j", version.ref = "password4j" }
cloud-core = { module = "cloud.commandframework:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "cloud.commandframework:cloud-annotations", version.ref = "cloud" }
cloud-javacord = { module = "cloud.commandframework:cloud-javacord", version.ref = "cloud" }
javacord-api = { module = "org.javacord:javacord-api", version.ref = "javacord" }
javacord-core = { module = "org.javacord:javacord-core", version.ref = "javacord" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
owner-java8 = { module = "org.aeonbits.owner:owner-java8", version.ref = "owner" }
distributor-api = { module = "fr.xpdustry:distributor-api", version.ref = "distributor" }
log4j-to-slf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4j-to-slf4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto" }
auto-service-processor = { module = "com.google.auto.service:auto-service", version.ref = "auto" }

# Plugins
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-licenser-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
toxopid = { module = "fr.xpdustry:toxopid", version.ref = "toxopid" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
shadow = { module = "gradle.plugin.com.github.johnrengelman:shadow", version.ref = "shadow" }
